### ISSUE TITLE
Missing highlight of first word (if bad word) with redactor

### ISSUE THREAD

**Issue by stefano-salari** [badsyntax/jquery-spellchecker#48]
If the very first word entered in the redactor component is a bad word, it's not highlighted by the spellchecker plugin. This issue may be reproduced also in the demo section of the spellchecker (http://jquery-spellchecker.badsyntax.co/redactor.html).

Note that adding a space before the word, as first character, all works fine.

Here a screenshot of the issue:

![issue](https://f.cloud.github.com/assets/2777590/738129/99cfea7c-e33f-11e2-9653-f5d24bf864c1.png)

**Comment by stefano-salari** [comment]
I have solved the problem in my project with a patch in the spellchecker.js code. What I changed it's the regex declared at line 588. The regex was:

```
var regExp = '';
regExp += '([^' + letterChars + '])';
regExp += '(' + incorrectWords.join('|') + ')';
regExp += '(?=[^' + letterChars + '])';
```

I changed with:

```
var regExp = '';
regExp += '([^' + letterChars + ']*)';
regExp += '(' + incorrectWords.join('|') + ')';
regExp += '(?=[^' + letterChars + ']*)';
```

In my project it seems to solve the problem, I don't know if it introduces issues in other cases but it might be a hint for you.

Please, let me know if I can help somehow.

**Comment by binario200** [comment]
Great job man, my QA team reports me that missing highlight word as a bug; As same as you I don't know it this could impact other functionality of the spellchecker. 

Thank you.

**Comment by stefano-salari** [comment]
Thank you for your reply! Please, let me know if I can help you.

**Comment by SugarRoll** [comment]
It works on the highlighting but when we choose a word from the suggestions, the word is not modified.

**Comment by tomatau** [comment]
I've fixed this bug by reusing the Regex from the text parser

```
        var regExp = '';
        regExp += '(^|[^' + letterChars + '])';
        regExp += '(' + incorrectWords.join('|') + ')';
        regExp += '(?=[^' + letterChars + ']|$)';
```

**Comment by bryandevvv** [comment]
I'm still having this same issue, though in a contenteditable div.  The first word will not be highlighted, and also a word right after a newline ("br" inside div).

I tried the regex mentioned above:
var regExp = '';
regExp += '([^' + letterChars + ']_)';
regExp += '(' + incorrectWords.join('|') + ')';
regExp += '(?=[^' + letterChars + ']_)';
and also one mentioned in similar listed bug:
var regExp = '';
regExp += '([^' + letterChars + ']?)';
regExp += '(' + incorrectWords.join('|') + ')';
regExp += '(?=[^' + letterChars + ']?)';

Both fix the issue of first word being highlighted, BUT they both also allow words within words to be highlighted.  Like "booz" is one of the words and marked misspelled, but "booz" of "booze" is also highlighted.

Using the regex from elsewhere in the lib does not solve the first highlight or after newline highlight for me:
var regExp = '';
regExp += '(^|[^' + letterChars + '])';
regExp += '(' + incorrectWords.join('|') + ')';
regExp += '(?=[^' + letterChars + ']|$)';

Help!  

Thanks

**Comment by bendman** [comment]
The issue is worsened because **it joins words between nodes before checking them**.  This way, if you have a word like **foo**_bar_baz it will match across the inline styles.  This causes an issue with words at the ends of block level nodes though, for instance: `<p>wierd</p><p>wierd</p>` do not get highlighted because it is matching `wierdwierd` against `weird` when trying to hightlight.

This is fixable by adding a newline character before the closing tags of visually spaced block level elements.  This character isn't visible in the rendered HTML, but it does get transformed into a space when comparing, which turns the example into `wierd wierd` which matches.

Also, as mentioned above, it doesn't account for words at the beginning or end of the entire checked area, so we need to account for begin and end characters (^ and $).

**I fixed this in my code by doing this for the highlightWords function:**

```
  HtmlParser.prototype.highlightWords = function(incorrectWords, element) {
    if (!incorrectWords.length) {
      return;
    }

    // add newlines at block level elements, for cross-node matching later
    element.html(element.html().replace(/\n?(<((\/(div|p|td|th|li|dt|dd))|br\/?)>)/gi, '\n$1'));

    this.incorrectWords = incorrectWords;
    incorrectWords = $.map(incorrectWords, function(word) {
      return RegExp.escape(word);
    });

    var regExp = '';
    regExp += '(^|[^' + letterChars + '])';
    regExp += '(' + incorrectWords.join('|') + ')';
    regExp += '(?=[^' + letterChars + ']|$)';

    this.replaceText(new RegExp(regExp, 'g'), element[0], this.highlightWordsHandler(incorrectWords), 2);
  };
```

Notice the `element.html(...)` part which adds newlines to the ends of visually breaking block level elements, as well as the ^ and $ characters added to the `regExp` as others did above.
